# Generated by Django 4.1.5 on 2023-05-22 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0007_alter_item_options_alter_item_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='item',
            unique_together=set(),
        ),
    ]
