# Generated by Django 4.1.5 on 2023-05-22 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0009_alter_item_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='item',
            unique_together=set(),
        ),
    ]
