# Generated by Django 4.1.5 on 2023-05-22 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0010_alter_item_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='item',
            unique_together={('list', 'text')},
        ),
    ]
